WELCOME_MESSAGE = '''

 PPPPPP   LL       OOOOOO  TTTTTTTT  OOOOOO   LL       OOOOOO
 PP   PP  LL      OO    OO    TT    OO    OO  LL      OO    OO
 PPPPPP   LL      OO    OO    TT    OO    OO  LL      OO    OO
 PP       LL      OO    OO    TT    OO    OO  LL      OO    OO
 PP       LLLLLLL  OOOOOO     TT     OOOOOO   LLLLLLL  OOOOOO
'''

PLOTOLO_SCRIPT_THREAD_PREFIX = 'PLOTOLO_SCRIPT_THREAD'
SESSION_COOKIE_NAME = 'PLOTOLO_SESSION_ID'